import type { InboxPageShellAssemblyInputs, UseInboxPageShellInputsOptions } from './useInboxPageShellInputTypes';

export function buildInboxSidebarInputs(
  options: UseInboxPageShellInputsOptions,
): InboxPageShellAssemblyInputs['sidebar'] {
  return {
    workspace: {
      language: options.language,
      filter: options.filter,
      channelFilter: options.channelFilter,
      search: options.search,
      searchTags: options.searchTags,
      followUpOnly: options.followUpOnly,
      queueSortMode: options.queueSortMode,
      queueOwnerFilter: options.queueOwnerFilter,
      queueDensity: options.queueDensity,
      savedViews: options.savedViews,
      activeSavedViewId: options.activeSavedViewId,
      currentQueueViewDirty: options.currentQueueViewDirty,
      visibleFollowUpCount: options.visibleFollowUpCount,
      unifiedConversationList: options.queueConversationList,
      selectableVisibleCount: options.selectableVisibleCount,
      totalVisibleCount: options.totalVisibleCount,
      isUnifiedConversationLoading: options.isUnifiedConversationLoading,
      isSyncing: options.isSyncing,
      isWhatsAppBackgroundSyncing: options.isWhatsAppBackgroundSyncing,
      syncError: options.syncError,
      lastSyncAt: options.lastSyncAt,
      emails: options.emails,
      clients: options.clients,
      currentUser: options.currentUser,
    },
    selection: {
      selectedEmailId: options.selectedEmailId,
      selectedWhatsAppPhone: options.selectedWhatsAppPhone,
      selectedTelegramConversation: options.selectedTelegramConversation,
      selectedLiveChatConversation: options.selectedLiveChatConversation,
      selectedConversationIds: options.selectedConversationIds,
      selectedCount: options.selectedCount,
      allVisibleSelected: options.allVisibleSelected,
      someVisibleSelected: options.someVisibleSelected,
    },
    bulk: {
      bulkTagInput: options.bulkTagInput,
      bulkNoteInput: options.bulkNoteInput,
      bulkOwnerId: options.bulkOwnerId,
      bulkStage: options.bulkStage,
      bulkFollowUpAt: options.bulkFollowUpAt,
    },
    actions: {
      onFilterChange: options.handleFilterChange,
      onChannelFilterChange: options.handleChannelFilterChange,
      onSearchChange: options.setSearch,
      onSearchTagsChange: options.setSearchTags,
      onToggleFollowUpOnly: options.handleToggleFollowUpOnly,
      onClearFollowUpOnly: options.handleClearFollowUpOnly,
      onQueueSortModeChange: options.setQueueSortMode,
      onQueueOwnerFilterChange: options.setQueueOwnerFilter,
      onQueueDensityChange: options.setQueueDensity,
      onApplySavedView: options.applySavedView,
      onSaveSavedView: options.saveCurrentQueueView,
      onDeleteSavedView: options.deleteSavedQueueView,
      onSetDefaultSavedView: options.setDefaultSavedQueueView,
      onResetQueueView: options.resetQueueView,
      onSync: options.handleSync,
      onComposeEmail: options.handleComposeEmail,
      onStartWhatsApp: options.handleStartWhatsApp,
      onToggleSelectAll: options.toggleSelectAll,
      onClearSelection: options.clearBulkSelection,
      onBulkTagInputChange: options.setBulkTagInput,
      onBulkNoteInputChange: options.setBulkNoteInput,
      onBulkOwnerIdChange: options.setBulkOwnerId,
      onBulkStageChange: options.setBulkStage,
      onBulkFollowUpAtChange: options.setBulkFollowUpAt,
      onAddTag: options.handleBulkAddTag,
      onAddComment: options.handleBulkAddComment,
      onAssignOwner: options.handleBulkAssignOwner,
      onSetStage: options.handleBulkSetStage,
      onSetFollowUp: options.handleBulkSetFollowUp,
      onMarkImportant: options.handleBulkMarkImportant,
      onDeleteSelected: options.handleDeleteSelected,
      onSelectConversation: options.handleSelectUnifiedConversation,
      onToggleConversationSelection: options.toggleUnifiedSelection,
      onDeleteWhatsAppConversation: options.handleDeleteWhatsAppConversation,
      onOwnerStageChange: options.updateConversationOwnerStage,
    },
  };
}
