import type { EmailMessage } from '../../store';
import type { InboxPageShellAssemblyInputs, UseInboxPageShellInputsOptions } from './useInboxPageShellInputTypes';

export function buildInboxContentPanelInputs(
  options: UseInboxPageShellInputsOptions,
): InboxPageShellAssemblyInputs['contentPanel'] {
  return {
    compose: {
      isComposing: options.isComposing,
      composeDefaults: options.composeDefaults,
      setIsComposing: options.setIsComposing,
      isStartingWhatsApp: options.isStartingWhatsApp,
      setIsStartingWhatsApp: options.setIsStartingWhatsApp,
      newWhatsAppPhone: options.newWhatsAppPhone,
      visibleWhatsAppContactOptions: options.visibleWhatsAppContactOptions,
      setNewWhatsAppPhone: options.setNewWhatsAppPhone,
      setShowWhatsAppContactPicker: options.setShowWhatsAppContactPicker,
      selectedWhatsAppClientId: options.selectedWhatsAppClientId,
      setSelectedWhatsAppClientId: options.setSelectedWhatsAppClientId,
      selectWhatsAppContactOption: options.selectWhatsAppContactOption,
      startNewWhatsApp: options.startNewWhatsApp,
    },
    telegram: {
      selectedTelegramConversation: options.selectedTelegramConversation,
      activeTelegramClient: options.activeConversationState.activeTelegramClient,
      activeTelegramContactMethod: options.activeConversationState.activeTelegramContactMethod,
      activeTelegramDisplayName: options.activeConversationState.activeTelegramDisplayName,
      activeTelegramTranslateEnabled: options.activeConversationState.activeTelegramTranslateEnabled,
      activeTelegramTranslations: options.activeConversationState.activeTelegramTranslations,
      activeTelegramAgentContext: options.activeConversationState.activeTelegramAgentContext,
      telegramMessages: options.telegramMessages,
      isTelegramMessagesLoading: options.isTelegramMessagesLoading,
      telegramReply: options.telegramReply,
      isSendingTelegramReply: options.isSendingTelegramReply,
      setSelectedTelegramConversation: options.setSelectedTelegramConversation,
      setTelegramMessages: options.setTelegramMessages,
      toggleTelegramHumanTakeover: options.toggleTelegramHumanTakeover,
      draftTelegramReply: options.draftTelegramReply,
      setTelegramReply: options.setTelegramReply,
      sendTelegramReply: options.sendTelegramReply,
    },
    liveChat: {
      selectedLiveChatConversation: options.selectedLiveChatConversation,
      activeLiveChatClient: options.activeConversationState.activeLiveChatClient,
      activeLiveChatContactMethod: options.activeConversationState.activeLiveChatContactMethod,
      activeLiveChatSession: options.activeConversationState.activeLiveChatSession,
      activeLiveChatTranslateEnabled: options.activeConversationState.activeLiveChatTranslateEnabled,
      activeLiveChatTranslations: options.activeConversationState.activeLiveChatTranslations,
      activeLiveChatVisitorInfo: options.activeConversationState.activeLiveChatVisitorInfo,
      activeLiveChatEvidenceItems: options.activeConversationState.activeLiveChatEvidenceItems,
      activeLiveChatAgentContext: options.activeConversationState.activeLiveChatAgentContext,
      visibleLiveChatMessages: options.activeConversationState.visibleLiveChatMessages,
      liveChatReply: options.liveChatReply,
      isSendingLiveChatReply: options.isSendingLiveChatReply,
      isRunningLiveChatAgent: options.isRunningLiveChatAgent,
      latestLiveChatVisitorMessage: options.activeConversationState.latestLiveChatVisitorMessage,
      liveChatEndRef: options.liveChatEndRef,
      setSelectedLiveChatConversation: options.setSelectedLiveChatConversation,
      toggleLiveChatHumanTakeover: options.toggleLiveChatHumanTakeover,
      runSelectedLiveChatAgent: options.runSelectedLiveChatAgent,
      setLiveChatReply: options.setLiveChatReply,
      sendLiveChatReply: options.sendLiveChatReply,
    },
    whatsapp: {
      selectedWhatsAppPhone: options.selectedWhatsAppPhone,
      setSelectedWhatsAppPhone: options.setSelectedWhatsAppPhone,
      activeWhatsAppConversation: options.activeConversationState.activeWhatsAppConversation,
      activeWhatsAppClient: options.activeConversationState.activeWhatsAppClient,
      handleDeleteWhatsAppConversation: options.handleDeleteWhatsAppConversation,
      loadWhatsAppConversations: options.loadWhatsAppConversations,
    },
    email: {
      selectedEmail: options.selectedEmailState.selectedEmail,
      clients: options.clients,
      isInboundCustomerEmail: (email: EmailMessage) => ['inbox', 'inbound'].includes(email.type),
      addingToRag: options.addingToRag,
      addedToRagId: options.addedToRagId,
      selectedTrackingEvents: options.selectedEmailState.selectedTrackingEvents,
      visibleTrackingEvents: options.selectedEmailState.visibleTrackingEvents,
      isTrackingExpanded: options.selectedEmailState.isTrackingExpanded,
      selectedEmailAgentContext: options.selectedEmailState.selectedEmailAgentContext,
      latestInboundEmailForSelectedClient: options.selectedEmailState.latestInboundEmailForSelectedClient,
      selectEmail: options.selectEmail,
      setComposeDefaults: options.setComposeDefaults,
      handleAddToRag: options.handleAddToRag,
      toggleTrackingExpanded: options.selectedEmailState.toggleTrackingExpanded,
      editEmail: options.editEmail,
    },
    shared: {
      language: options.language,
      currentUser: options.currentUser,
      translatingConversationMessageIds: options.translationState.translatingConversationMessageIds,
      activeConversationComments: options.commentsState.activeConversationComments,
      commentText: options.commentText,
      activeFollowUpAt: options.followUpState.activeFollowUpAt,
      activeFollowUpNote: options.followUpState.activeFollowUpNote,
      selectClient: options.selectClient,
      updateConversationOwnerStage: options.updateConversationOwnerStage,
      setConfirmDialog: options.setConfirmDialog,
      deleteUnifiedConversation: options.deleteUnifiedConversation,
      refreshUnifiedConversationData: options.refreshUnifiedConversationData,
      setConversationAutoTranslateEnabled: options.setConversationAutoTranslateEnabled,
      handleCreateLead: options.handleCreateLead,
      setIsAddingContactToClient: options.setIsAddingContactToClient,
      patchUnifiedConversation: options.patchUnifiedConversation,
      applyUnifiedConversationUpdate: options.applyUnifiedConversationUpdate,
      appendActiveConversationComment: options.appendActiveConversationComment,
      updateActiveConversationFollowUp: options.updateActiveConversationFollowUp,
      setCommentText: options.setCommentText,
      replyActiveConversationComment: options.replyActiveConversationComment,
      activeUnifiedConversation: options.activeConversationState.activeUnifiedConversation,
      commentAttachments: options.commentAttachments,
      setShowCommentAttachmentModal: options.setShowCommentAttachmentModal,
      setCommentAttachments: options.setCommentAttachments,
    },
  };
}
