import React, { useMemo, useRef } from 'react';
import { EmailMessage } from '../store';
import {
  CONVERSATION_STAGES,
  InboxPageShell,
  useActiveConversationComments,
  useActiveConversationContext,
  useConversationFollowUp,
  useConversationReplyActions,
  useConversationTranslations,
  useEmailQuickActions,
  useInboxConversationList,
  useInboxConversationSlices,
  useInboxFollowUpFilterRequest,
  useInboxLifecycleEffects,
  useInboxNavigationActions,
  useInboxPageShellAssembly,
  useInboxPageShellInputs,
  useInboxPageShellOptions,
  useInboxQueueConversationList,
  useInboxQueueWorkspace,
  useInboxSavedViews,
  useInboxSidebarActions,
  useInboxSync,
  useInboxUiState,
  useInboxWorkspaceData,
  useLiveChatInboxSession,
  useSelectedEmailContext,
  useUnifiedConversationActions,
  WHATSAPP_FOLLOW_UP_MARKER,
} from './inbox-ui';
import type {
  InboxWhatsAppConversation,
  UnifiedCommunicationConversation,
} from './inbox-ui';

export function Inbox() {
  const {
    emails,
    markEmailRead,
    clients,
    logs,
    deals,
    knowledgeBase,
    products,
    addEmail,
    addLog,
    addClient,
    editClient,
    editEmail,
    addEmailComment,
    addEmailReply,
    addQuest,
    selectClient,
    addKnowledgeItem,
    selectedEmailId,
    selectEmail,
    notify,
    language,
    llmConfigs,
    activeLLMId,
    llmMappings,
    inboxFollowUpFilterRequest,
    fetchEmails,
    fetchLiveChatSessions,
    fetchLiveChatMessages,
    sendLiveChatOperatorMessage,
    updateLiveChatSession,
    runLiveChatAgent,
    connectLiveChatSocket,
    joinLiveChatSocketSession,
    liveChatSessions,
    liveChatMessages,
    liveChatSocketStatus,
    currentUser,
  } = useInboxWorkspaceData();
  const defaultQueueView = useMemo(() => ({
    filter: 'inbox' as const,
    channelFilter: 'all' as const,
    search: '',
    searchTags: [] as string[],
    followUpOnly: false,
    queueSortMode: 'recent' as const,
    queueOwnerFilter: 'all' as const,
    queueDensity: 'comfortable' as const,
  }), []);
  const {
    filter,
    setFilter,
    channelFilter,
    setChannelFilter,
    emailListMode,
    setEmailListMode,
    search,
    setSearch,
    searchTags,
    setSearchTags,
    followUpOnly,
    setFollowUpOnly,
    queueSortMode,
    setQueueSortMode,
    queueOwnerFilter,
    setQueueOwnerFilter,
    queueDensity,
    setQueueDensity,
    isComposing,
    setIsComposing,
    composeDefaults,
    setComposeDefaults,
    commentText,
    setCommentText,
    commentAttachments,
    setCommentAttachments,
    showCommentAttachmentModal,
    setShowCommentAttachmentModal,
    isCreatingLead,
    setIsCreatingLead,
    isAddingContactToClient,
    setIsAddingContactToClient,
    bulkTagInput,
    setBulkTagInput,
    bulkNoteInput,
    setBulkNoteInput,
    bulkFollowUpAt,
    setBulkFollowUpAt,
    bulkOwnerId,
    setBulkOwnerId,
    bulkStage,
    setBulkStage,
    activeMenu,
    setActiveMenu,
    todoModalEmail,
    setTodoModalEmail,
    todoAt,
    setTodoAt,
    todoNote,
    setTodoNote,
    tagModalEmail,
    setTagModalEmail,
    tagInput,
    setTagInput,
    unifiedConversations,
    setUnifiedConversations,
    selectedWhatsAppPhone,
    setSelectedWhatsAppPhone,
    selectedWhatsAppClientId,
    setSelectedWhatsAppClientId,
    selectedTelegramConversation,
    setSelectedTelegramConversation,
    telegramMessages,
    setTelegramMessages,
    selectedLiveChatConversation,
    setSelectedLiveChatConversation,
    isStartingWhatsApp,
    setIsStartingWhatsApp,
    newWhatsAppPhone,
    setNewWhatsAppPhone,
    showWhatsAppContactPicker,
    setShowWhatsAppContactPicker,
    confirmDialog,
    setConfirmDialog,
    alertDialog,
    setAlertDialog,
  } = useInboxUiState();
  const {
    isSyncing,
    lastSyncAt,
    syncError,
    isUnifiedConversationLoading,
    whatsappConversations,
    setWhatsappConversations,
    isWhatsAppBackgroundSyncing,
    updateWhatsAppConversationState,
    fetchUnifiedConversations,
    syncWhatsAppConversations,
    loadWhatsAppConversations,
    handleSync,
  } = useInboxSync({
    search,
    searchTags,
    fetchEmails,
    fetchLiveChatSessions,
    notify,
    setUnifiedConversations,
  });
  const liveChatEndRef = useRef<HTMLDivElement | null>(null);
  const isInboundCustomerEmail = (email: EmailMessage) => ['inbox', 'inbound'].includes(email.type);

  const {
    conversationAutoTranslateConfig,
    conversationTranslations,
    translatingConversationMessageIds,
    setConversationAutoTranslateEnabled,
  } = useConversationTranslations({
    language,
    llmConfigs,
    activeLLMId,
    llmMappings,
    selectedTelegramConversation,
    telegramMessages,
    selectedLiveChatConversation,
    liveChatMessages,
  });

  useInboxLifecycleEffects({
    search,
    searchTags,
    setActiveMenu,
    loadWhatsAppConversations,
    fetchUnifiedConversations,
    syncWhatsAppConversations,
    handleSync,
  });

  const {
    unifiedConversationSource,
    unifiedConversationList,
    visibleFollowUpCount,
    visibleWhatsAppContactOptions,
  } = useInboxConversationList({
    filter,
    channelFilter,
    search,
    searchTags,
    followUpOnly,
    emails,
    clients,
    whatsappConversations,
    unifiedConversations,
    newWhatsAppPhone,
    showWhatsAppContactPicker,
  });

  const queueConversationList = useInboxQueueConversationList({
    unifiedConversationList,
    currentUserId: currentUser?.id,
    queueOwnerFilter,
    queueSortMode,
  });

  const currentQueueView = useMemo(() => ({
    filter,
    channelFilter,
    search,
    searchTags,
    followUpOnly,
    queueSortMode,
    queueOwnerFilter,
    queueDensity,
  }), [channelFilter, filter, followUpOnly, queueDensity, queueOwnerFilter, queueSortMode, search, searchTags]);

  const {
    savedViews,
    activeSavedViewId,
    currentQueueViewDirty,
    applySavedView,
    saveCurrentQueueView,
    deleteSavedQueueView,
    setDefaultSavedQueueView,
    resetQueueView,
  } = useInboxSavedViews({
    defaultQueueView,
    currentQueueView,
    setFilter,
    setChannelFilter,
    setSearch,
    setSearchTags,
    setFollowUpOnly,
    setQueueSortMode,
    setQueueOwnerFilter,
    setQueueDensity,
  });

  const activeQueueWhatsAppConversation = useMemo(
    () =>
      whatsappConversations.find(
        conversation =>
          conversation.targetPhone === selectedWhatsAppPhone
          && (!selectedWhatsAppClientId
            || conversation.clientId === selectedWhatsAppClientId),
      ) ?? null,
    [selectedWhatsAppClientId, selectedWhatsAppPhone, whatsappConversations],
  );

  const {
    addWhatsAppConversationComment,
    patchUnifiedConversation,
    deleteUnifiedConversation,
    applyUnifiedConversationUpdate,
    updateConversationOwnerStage,
    findEmailUnifiedConversation,
    refreshUnifiedConversationData,
  } = useUnifiedConversationActions({
    language,
    unifiedConversationSource,
    setUnifiedConversations,
    fetchUnifiedConversations,
    fetchEmails,
    fetchLiveChatSessions,
    notify,
  });

  const {
    selectedIds,
    selectedWhatsAppIds,
    selectedConversationIds,
    selectedCount,
    selectableVisibleCount,
    totalVisibleCount,
    allVisibleSelected,
    someVisibleSelected,
    toggleUnifiedSelection,
    toggleSelectAll,
    clearBulkSelection,
    handleDeleteSelected,
    handleBulkAddTag,
    handleBulkMarkImportant,
    handleBulkAddComment,
    handleBulkSetFollowUp,
    handleBulkAssignOwner,
    handleBulkSetStage,
  } = useInboxQueueWorkspace({
    unifiedConversationList: queueConversationList,
    emails,
    whatsappConversations,
    unifiedConversations,
    language,
    selectedEmailId,
    activeWhatsAppConversation: activeQueueWhatsAppConversation,
    clients,
    bulkTagInput,
    bulkNoteInput,
    bulkFollowUpAt,
    bulkOwnerId,
    bulkStage,
    setBulkTagInput,
    setBulkNoteInput,
    setBulkFollowUpAt,
    setBulkOwnerId,
    setBulkStage,
    setConfirmDialog,
    setSelectedWhatsAppPhone,
    selectEmail,
    editClient,
    notify,
    patchUnifiedConversation,
    deleteUnifiedConversation,
    applyUnifiedConversationUpdate,
    refreshUnifiedConversationData,
    updateWhatsAppConversationState,
  });

  useInboxFollowUpFilterRequest({
    request: inboxFollowUpFilterRequest,
    clearBulkSelection,
    selectEmail,
    setFilter,
    setChannelFilter,
    setEmailListMode,
    setFollowUpOnly,
    setIsComposing,
    setIsStartingWhatsApp,
    setSelectedWhatsAppPhone,
    setSelectedWhatsAppClientId,
    setSelectedTelegramConversation,
    setSelectedLiveChatConversation,
  });

  const {
    handleFilterChange,
    handleChannelFilterChange,
    handleToggleFollowUpOnly,
    handleClearFollowUpOnly,
    handleComposeEmail,
    handleStartWhatsApp,
  } = useInboxSidebarActions({
    selectedWhatsAppPhone,
    selectEmail,
    clearBulkSelection,
    setFilter,
    setChannelFilter,
    setEmailListMode,
    setFollowUpOnly,
    setIsComposing,
    setComposeDefaults,
    setIsStartingWhatsApp,
    setSelectedWhatsAppPhone,
    setSelectedWhatsAppClientId,
    setSelectedTelegramConversation,
    setTelegramMessages,
    setSelectedLiveChatConversation,
  });

  useLiveChatInboxSession({
    selectedLiveChatConversation,
    liveChatMessages,
    liveChatSocketStatus,
    liveChatEndRef,
    connectLiveChatSocket,
    joinLiveChatSocketSession,
    fetchLiveChatMessages,
    patchUnifiedConversation,
    refreshUnifiedConversationData,
  });

  const {
    selectedEmail,
    selectedEmailIsInbound,
    selectedEmailContactAddress,
    selectedEmailClient,
    latestInboundEmailForSelectedClient,
    selectedEmailAgentContext,
    selectedTrackingEvents,
    isTrackingExpanded,
    visibleTrackingEvents,
    toggleTrackingExpanded,
  } = useSelectedEmailContext({
    selectedEmailId,
    emails,
    clients,
    logs,
    deals,
    knowledgeBase,
    products,
    filter,
    setFilter,
  });

  const {
    activeWhatsAppConversation,
    activeWhatsAppClient,
    activeWhatsAppFollowUp,
    activeTelegramClient,
    activeTelegramContactMethod,
    activeTelegramDisplayName,
    activeTelegramTranslateEnabled,
    activeTelegramTranslations,
    activeTelegramAgentContext,
    activeLiveChatSession,
    activeLiveChatMessages,
    activeLiveChatTranslateEnabled,
    activeLiveChatTranslations,
    visibleLiveChatMessages,
    activeLiveChatClient,
    activeLiveChatVisitorInfo,
    latestLiveChatVisitorMessage,
    activeLiveChatEvidenceItems,
    activeLiveChatContactMethod,
    activeLiveChatDisplayName,
    activeLiveChatAgentContext,
    activeLinkableContactMethod,
    activeLinkableDisplayName,
    activeUnifiedConversation,
  } = useActiveConversationContext({
    language,
    clients,
    emails,
    logs,
    deals,
    knowledgeBase,
    products,
    conversationAutoTranslateConfig,
    conversationTranslations,
    liveChatSessions,
    liveChatMessages,
    selectedEmail,
    selectedEmailContactAddress,
    selectedWhatsAppPhone,
    selectedWhatsAppClientId,
    selectedTelegramConversation,
    telegramMessages,
    selectedLiveChatConversation,
    unifiedConversationSource,
    whatsappConversations,
  });

  const {
    activeConversationComments,
    appendActiveConversationComment,
    replyActiveConversationComment,
  } = useActiveConversationComments({
    selectedTelegramConversation,
    activeTelegramClient,
    selectedLiveChatConversation,
    activeLiveChatClient,
    activeUnifiedConversation,
    selectedEmail,
    activeWhatsAppConversation,
    whatsappConversations,
    editClient,
    addEmailComment,
    addEmailReply,
    patchUnifiedConversation,
    refreshUnifiedConversationData,
    addWhatsAppConversationComment,
    updateWhatsAppConversationState,
  });

  const {
    activeFollowUpAt,
    activeFollowUpNote,
    updateActiveConversationFollowUp,
  } = useConversationFollowUp({
    activeUnifiedConversation,
    selectedEmail,
    activeWhatsAppConversation,
    whatsappConversations,
    activeWhatsAppFollowUp,
    language,
    editEmail,
    patchUnifiedConversation,
    applyUnifiedConversationUpdate,
    addWhatsAppConversationComment,
    updateWhatsAppConversationState,
    appendActiveConversationComment,
    notify,
    whatsappFollowUpMarker: WHATSAPP_FOLLOW_UP_MARKER,
  });

  const {
    telegramReply,
    setTelegramReply,
    isSendingTelegramReply,
    isTelegramMessagesLoading,
    loadTelegramMessages,
    sendTelegramReply,
    draftTelegramReply,
    toggleTelegramHumanTakeover,
    liveChatReply,
    setLiveChatReply,
    isSendingLiveChatReply,
    sendLiveChatReply,
    toggleLiveChatHumanTakeover,
    isRunningLiveChatAgent,
    runSelectedLiveChatAgent,
  } = useConversationReplyActions({
    language,
    selectedTelegramConversation,
    setSelectedTelegramConversation,
    setTelegramMessages,
    selectedLiveChatConversation,
    setSelectedLiveChatConversation,
    activeLiveChatSession,
    activeTelegramClient,
    activeTelegramAgentContext,
    llmMappings,
    activeLLMId,
    llmConfigs,
    sendLiveChatOperatorMessage,
    updateLiveChatSession,
    runLiveChatAgent,
    fetchLiveChatMessages,
    patchUnifiedConversation,
    refreshUnifiedConversationData,
    notify,
  });

  const {
    handleSelect,
    handleSelectWhatsApp,
    handleSelectUnifiedConversation,
    handleDeleteWhatsAppConversation,
    startNewWhatsApp,
    selectWhatsAppContactOption,
    handleCreateLead,
  } = useInboxNavigationActions({
    whatsappConversations,
    unifiedConversationSource,
    selectedEmail,
    selectedEmailId,
    selectedWhatsAppPhone,
    selectedLiveChatConversation,
    selectedTelegramConversation,
    activeLiveChatClient,
    activeLiveChatContactMethod,
    activeTelegramClient,
    activeTelegramContactMethod,
    newWhatsAppPhone,
    markEmailRead,
    selectEmail,
    setIsComposing,
    setComposeDefaults,
    setIsStartingWhatsApp,
    setSelectedWhatsAppPhone,
    setSelectedWhatsAppClientId,
    setSelectedTelegramConversation,
    setTelegramMessages,
    setTelegramReply,
    setSelectedLiveChatConversation,
    setLiveChatReply,
    setWhatsappConversations,
    setNewWhatsAppPhone,
    setShowWhatsAppContactPicker,
    setChannelFilter,
    setIsCreatingLead,
    setConfirmDialog,
    findEmailUnifiedConversation,
    patchUnifiedConversation,
    deleteUnifiedConversation,
    refreshUnifiedConversationData,
    loadTelegramMessages,
    fetchLiveChatMessages,
    fetchLiveChatSessions,
    notify,
  });

  const {
    submitTag,
    submitTodo,
    addingToRag,
    addedToRagId,
    toggleImportant,
    handleAddToRag,
  } = useEmailQuickActions({
    selectedEmail,
    emails,
    todoModalEmail,
    todoAt,
    todoNote,
    tagModalEmail,
    tagInput,
    language,
    llmMappings,
    activeLLMId,
    llmConfigs,
    setTodoModalEmail,
    setTodoAt,
    setTodoNote,
    setTagModalEmail,
    setTagInput,
    setActiveMenu,
    editEmail,
    addKnowledgeItem,
    findEmailUnifiedConversation,
    patchUnifiedConversation,
    refreshUnifiedConversationData,
    notify,
  });

  const {
    selectedEmailState,
    activeConversationState,
    commentsState,
    followUpState,
    translationState,
  } = useInboxConversationSlices({
    selectedEmail,
    selectedEmailIsInbound,
    selectedEmailContactAddress,
    selectedEmailClient,
    latestInboundEmailForSelectedClient,
    selectedEmailAgentContext,
    selectedTrackingEvents,
    isTrackingExpanded,
    visibleTrackingEvents,
    toggleTrackingExpanded,
    activeWhatsAppConversation,
    activeWhatsAppClient,
    activeWhatsAppFollowUp,
    activeTelegramClient,
    activeTelegramContactMethod,
    activeTelegramDisplayName,
    activeTelegramTranslateEnabled,
    activeTelegramTranslations,
    activeTelegramAgentContext,
    activeLiveChatSession,
    activeLiveChatMessages,
    activeLiveChatTranslateEnabled,
    activeLiveChatTranslations,
    visibleLiveChatMessages,
    activeLiveChatClient,
    activeLiveChatVisitorInfo,
    latestLiveChatVisitorMessage,
    activeLiveChatEvidenceItems,
    activeLiveChatContactMethod,
    activeLiveChatDisplayName,
    activeLiveChatAgentContext,
    activeLinkableContactMethod,
    activeLinkableDisplayName,
    activeUnifiedConversation,
    activeConversationComments,
    appendActiveConversationComment,
    replyActiveConversationComment,
    activeFollowUpAt,
    activeFollowUpNote,
    updateActiveConversationFollowUp,
    conversationAutoTranslateConfig,
    conversationTranslations,
    translatingConversationMessageIds,
    setConversationAutoTranslateEnabled,
  });

  const pageShellOptions = useInboxPageShellOptions({
    workspace: {
      language,
      currentUser,
      clients,
      emails,
      editEmail,
      selectEmail,
      selectClient,
    },
    queue: {
      filter,
      channelFilter,
      search,
      searchTags,
      followUpOnly,
      queueSortMode,
      queueOwnerFilter,
      queueDensity,
      savedViews,
      activeSavedViewId,
      currentQueueViewDirty,
      visibleFollowUpCount,
      queueConversationList,
      selectableVisibleCount,
      totalVisibleCount,
      isUnifiedConversationLoading,
      isSyncing,
      isWhatsAppBackgroundSyncing,
      syncError,
      lastSyncAt,
      selectedConversationIds,
      selectedCount,
      allVisibleSelected,
      someVisibleSelected,
      bulkTagInput,
      setBulkTagInput,
      bulkNoteInput,
      setBulkNoteInput,
      bulkOwnerId,
      setBulkOwnerId,
      bulkStage,
      setBulkStage,
      bulkFollowUpAt,
      setBulkFollowUpAt,
      applySavedView,
      saveCurrentQueueView,
      deleteSavedQueueView,
      setDefaultSavedQueueView,
      resetQueueView,
      handleFilterChange,
      handleChannelFilterChange,
      handleToggleFollowUpOnly,
      handleClearFollowUpOnly,
      handleBulkAddTag,
      handleBulkAddComment,
      handleBulkAssignOwner,
      handleBulkSetStage,
      handleBulkSetFollowUp,
      handleBulkMarkImportant,
      handleDeleteSelected,
      toggleSelectAll,
      clearBulkSelection,
      setSearch,
      setSearchTags,
      setQueueSortMode,
      setQueueOwnerFilter,
      setQueueDensity,
    },
    selection: {
      selectedEmailId,
      selectedWhatsAppPhone,
      selectedWhatsAppClientId,
      selectedTelegramConversation,
      selectedLiveChatConversation,
      setSelectedWhatsAppPhone,
      setSelectedWhatsAppClientId,
      setSelectedTelegramConversation,
      setTelegramMessages,
      setSelectedLiveChatConversation,
      handleSelectUnifiedConversation,
      toggleUnifiedSelection,
      updateConversationOwnerStage,
      patchUnifiedConversation,
      deleteUnifiedConversation,
      applyUnifiedConversationUpdate,
      refreshUnifiedConversationData,
    },
    compose: {
      isComposing,
      setIsComposing,
      composeDefaults,
      setComposeDefaults,
      isStartingWhatsApp,
      setIsStartingWhatsApp,
      newWhatsAppPhone,
      visibleWhatsAppContactOptions,
      setNewWhatsAppPhone,
      setShowWhatsAppContactPicker,
      isCreatingLead,
      setIsCreatingLead,
      isAddingContactToClient,
      setIsAddingContactToClient,
      commentText,
      setCommentText,
      commentAttachments,
      setCommentAttachments,
      showCommentAttachmentModal,
      setShowCommentAttachmentModal,
      confirmDialog,
      setConfirmDialog,
      alertDialog,
      setAlertDialog,
      tagModalEmail,
      setTagModalEmail,
      tagInput,
      setTagInput,
      todoModalEmail,
      setTodoModalEmail,
      todoAt,
      setTodoAt,
      todoNote,
      setTodoNote,
    },
    channelWorkspace: {
      telegramMessages,
      isTelegramMessagesLoading,
      telegramReply,
      isSendingTelegramReply,
      setTelegramReply,
      toggleTelegramHumanTakeover,
      draftTelegramReply,
      sendTelegramReply,
      liveChatReply,
      isSendingLiveChatReply,
      isRunningLiveChatAgent,
      liveChatEndRef,
      setLiveChatReply,
      toggleLiveChatHumanTakeover,
      runSelectedLiveChatAgent,
      sendLiveChatReply,
      handleComposeEmail,
      handleStartWhatsApp,
      handleSync,
      loadWhatsAppConversations,
      handleDeleteWhatsAppConversation,
      selectWhatsAppContactOption,
      startNewWhatsApp,
      handleCreateLead,
      updateLiveChatSession,
      fetchLiveChatSessions,
    },
    conversationState: {
      selectedEmailState,
      activeConversationState,
      commentsState,
      followUpState,
      translationState,
      addingToRag,
      addedToRagId,
      handleAddToRag,
      submitTag,
      submitTodo,
      setConversationAutoTranslateEnabled,
      appendActiveConversationComment,
      updateActiveConversationFollowUp,
      replyActiveConversationComment,
    },
  });

  const pageShellInputs = useInboxPageShellInputs(pageShellOptions);

  const {
    sidebarHidden,
    contentHidden,
    sidebarProps,
    contentPanelProps,
    dialogLayerProps,
  } = useInboxPageShellAssembly(pageShellInputs);

  return (
    <InboxPageShell
      sidebarHidden={sidebarHidden}
      contentHidden={contentHidden}
      sidebarProps={sidebarProps}
      contentPanelProps={contentPanelProps}
      dialogLayerProps={dialogLayerProps}
    />
  );
}

export { ComposeEmail } from './inbox-ui';
