import React, { useRef } from 'react';
import { useStore, EmailMessage } from '../store';
import { useAuthStore } from '../authStore';
import {
  CONVERSATION_STAGES,
  InboxPageShell,
  useActiveConversationComments,
  useActiveConversationContext,
  useConversationFollowUp,
  useConversationReplyActions,
  useConversationTranslations,
  useEmailQuickActions,
  useInboxBulkActions,
  useInboxConversationList,
  useInboxContentPanelProps,
  useInboxDialogLayerProps,
  useInboxFollowUpFilterRequest,
  useInboxLifecycleEffects,
  useInboxNavigationActions,
  useInboxPageVisibility,
  useInboxSelection,
  useInboxSidebarActions,
  useInboxSidebarProps,
  useInboxSync,
  useInboxUiState,
  useLiveChatInboxSession,
  useSelectedEmailContext,
  useUnifiedConversationActions,
  WHATSAPP_FOLLOW_UP_MARKER,
} from './inbox-ui';
import type {
  InboxChannelFilter,
  InboxWhatsAppConversation,
  UnifiedCommunicationConversation,
} from './inbox-ui';

export function Inbox() {
  const { emails, markEmailRead, clients, logs, deals, knowledgeBase, products, addEmail, addLog, addClient, editClient, editEmail, addEmailComment, addEmailReply, addQuest, selectClient, addKnowledgeItem, selectedEmailId, selectEmail, notify, language, llmConfigs, activeLLMId, llmMappings, inboxFollowUpFilterRequest, fetchEmails, fetchLiveChatSessions, fetchLiveChatMessages, sendLiveChatOperatorMessage, updateLiveChatSession, runLiveChatAgent, connectLiveChatSocket, joinLiveChatSocketSession, liveChatSessions, liveChatMessages, liveChatSocketStatus } = useStore();
  const currentUser = useAuthStore(state => state.profile);
  const {
    filter,
    setFilter,
    channelFilter,
    setChannelFilter,
    emailListMode,
    setEmailListMode,
    search,
    setSearch,
    searchTags,
    setSearchTags,
    followUpOnly,
    setFollowUpOnly,
    isComposing,
    setIsComposing,
    composeDefaults,
    setComposeDefaults,
    commentText,
    setCommentText,
    commentAttachments,
    setCommentAttachments,
    showCommentAttachmentModal,
    setShowCommentAttachmentModal,
    isCreatingLead,
    setIsCreatingLead,
    isAddingContactToClient,
    setIsAddingContactToClient,
    bulkTagInput,
    setBulkTagInput,
    bulkNoteInput,
    setBulkNoteInput,
    bulkFollowUpAt,
    setBulkFollowUpAt,
    bulkOwnerId,
    setBulkOwnerId,
    bulkStage,
    setBulkStage,
    activeMenu,
    setActiveMenu,
    todoModalEmail,
    setTodoModalEmail,
    todoAt,
    setTodoAt,
    todoNote,
    setTodoNote,
    tagModalEmail,
    setTagModalEmail,
    tagInput,
    setTagInput,
    unifiedConversations,
    setUnifiedConversations,
    selectedWhatsAppPhone,
    setSelectedWhatsAppPhone,
    selectedWhatsAppClientId,
    setSelectedWhatsAppClientId,
    selectedTelegramConversation,
    setSelectedTelegramConversation,
    telegramMessages,
    setTelegramMessages,
    selectedLiveChatConversation,
    setSelectedLiveChatConversation,
    isStartingWhatsApp,
    setIsStartingWhatsApp,
    newWhatsAppPhone,
    setNewWhatsAppPhone,
    showWhatsAppContactPicker,
    setShowWhatsAppContactPicker,
    confirmDialog,
    setConfirmDialog,
    alertDialog,
    setAlertDialog,
  } = useInboxUiState();
  const {
    isSyncing,
    lastSyncAt,
    syncError,
    isUnifiedConversationLoading,
    whatsappConversations,
    setWhatsappConversations,
    isWhatsAppBackgroundSyncing,
    updateWhatsAppConversationState,
    fetchUnifiedConversations,
    syncWhatsAppConversations,
    loadWhatsAppConversations,
    handleSync,
  } = useInboxSync({
    search,
    searchTags,
    fetchEmails,
    fetchLiveChatSessions,
    notify,
    setUnifiedConversations,
  });
  const liveChatEndRef = useRef<HTMLDivElement | null>(null);
  const isInboundCustomerEmail = (email: EmailMessage) => ['inbox', 'inbound'].includes(email.type);

  const {
    conversationAutoTranslateConfig,
    conversationTranslations,
    translatingConversationMessageIds,
    setConversationAutoTranslateEnabled,
  } = useConversationTranslations({
    language,
    llmConfigs,
    activeLLMId,
    llmMappings,
    selectedTelegramConversation,
    telegramMessages,
    selectedLiveChatConversation,
    liveChatMessages,
  });

  useInboxLifecycleEffects({
    search,
    searchTags,
    setActiveMenu,
    loadWhatsAppConversations,
    fetchUnifiedConversations,
    syncWhatsAppConversations,
    handleSync,
  });

  const {
    unifiedConversationSource,
    unifiedConversationList,
    visibleFollowUpCount,
    visibleWhatsAppContactOptions,
  } = useInboxConversationList({
    filter,
    channelFilter,
    search,
    searchTags,
    followUpOnly,
    emails,
    clients,
    whatsappConversations,
    unifiedConversations,
    newWhatsAppPhone,
    showWhatsAppContactPicker,
  });


  const {
    selectedIds,
    selectedWhatsAppIds,
    selectedConversationIds,
    selectedUnifiedConversations,
    selectedCount,
    selectableVisibleCount,
    totalVisibleCount,
    allVisibleSelected,
    someVisibleSelected,
    toggleUnifiedSelection,
    toggleSelectAll,
    clearBulkSelection,
  } = useInboxSelection({
    unifiedConversationList,
    emails,
    whatsappConversations,
    unifiedConversations,
  });

  useInboxFollowUpFilterRequest({
    request: inboxFollowUpFilterRequest,
    clearBulkSelection,
    selectEmail,
    setFilter,
    setChannelFilter,
    setEmailListMode,
    setFollowUpOnly,
    setIsComposing,
    setIsStartingWhatsApp,
    setSelectedWhatsAppPhone,
    setSelectedWhatsAppClientId,
    setSelectedTelegramConversation,
    setSelectedLiveChatConversation,
  });

  const {
    handleFilterChange,
    handleChannelFilterChange,
    handleToggleFollowUpOnly,
    handleClearFollowUpOnly,
    handleComposeEmail,
    handleStartWhatsApp,
  } = useInboxSidebarActions({
    selectedWhatsAppPhone,
    selectEmail,
    clearBulkSelection,
    setFilter,
    setChannelFilter,
    setEmailListMode,
    setFollowUpOnly,
    setIsComposing,
    setComposeDefaults,
    setIsStartingWhatsApp,
    setSelectedWhatsAppPhone,
    setSelectedWhatsAppClientId,
    setSelectedTelegramConversation,
    setTelegramMessages,
    setSelectedLiveChatConversation,
  });

  const {
    addWhatsAppConversationComment,
    patchUnifiedConversation,
    deleteUnifiedConversation,
    applyUnifiedConversationUpdate,
    updateConversationOwnerStage,
    findEmailUnifiedConversation,
    refreshUnifiedConversationData,
  } = useUnifiedConversationActions({
    language,
    unifiedConversationSource,
    setUnifiedConversations,
    fetchUnifiedConversations,
    fetchEmails,
    fetchLiveChatSessions,
    notify,
  });

  useLiveChatInboxSession({
    selectedLiveChatConversation,
    liveChatMessages,
    liveChatSocketStatus,
    liveChatEndRef,
    connectLiveChatSocket,
    joinLiveChatSocketSession,
    fetchLiveChatMessages,
    patchUnifiedConversation,
    refreshUnifiedConversationData,
  });

  const {
    selectedEmail,
    selectedEmailIsInbound,
    selectedEmailContactAddress,
    selectedEmailClient,
    latestInboundEmailForSelectedClient,
    selectedEmailAgentContext,
    selectedTrackingEvents,
    isTrackingExpanded,
    visibleTrackingEvents,
    toggleTrackingExpanded,
  } = useSelectedEmailContext({
    selectedEmailId,
    emails,
    clients,
    logs,
    deals,
    knowledgeBase,
    products,
    filter,
    setFilter,
  });

  const {
    activeWhatsAppConversation,
    activeWhatsAppClient,
    activeWhatsAppFollowUp,
    activeTelegramClient,
    activeTelegramContactMethod,
    activeTelegramDisplayName,
    activeTelegramTranslateEnabled,
    activeTelegramTranslations,
    activeTelegramAgentContext,
    activeLiveChatSession,
    activeLiveChatMessages,
    activeLiveChatTranslateEnabled,
    activeLiveChatTranslations,
    visibleLiveChatMessages,
    activeLiveChatClient,
    activeLiveChatVisitorInfo,
    latestLiveChatVisitorMessage,
    activeLiveChatEvidenceItems,
    activeLiveChatContactMethod,
    activeLiveChatDisplayName,
    activeLiveChatAgentContext,
    activeLinkableContactMethod,
    activeLinkableDisplayName,
    activeUnifiedConversation,
  } = useActiveConversationContext({
    language,
    clients,
    emails,
    logs,
    deals,
    knowledgeBase,
    products,
    conversationAutoTranslateConfig,
    conversationTranslations,
    liveChatSessions,
    liveChatMessages,
    selectedEmail,
    selectedEmailContactAddress,
    selectedWhatsAppPhone,
    selectedWhatsAppClientId,
    selectedTelegramConversation,
    telegramMessages,
    selectedLiveChatConversation,
    unifiedConversationSource,
    whatsappConversations,
  });

  const {
    handleDeleteSelected,
    handleBulkAddTag,
    handleBulkMarkImportant,
    handleBulkAddComment,
    handleBulkSetFollowUp,
    handleBulkAssignOwner,
    handleBulkSetStage,
  } = useInboxBulkActions({
    language,
    selectedCount,
    selectedUnifiedConversations,
    selectedIds,
    selectedWhatsAppIds,
    selectedEmailId,
    activeWhatsAppConversation,
    whatsappConversations,
    clients,
    bulkTagInput,
    bulkNoteInput,
    bulkFollowUpAt,
    bulkOwnerId,
    bulkStage,
    setBulkTagInput,
    setBulkNoteInput,
    setBulkFollowUpAt,
    setBulkOwnerId,
    setBulkStage,
    setConfirmDialog,
    setSelectedWhatsAppPhone,
    selectEmail,
    clearBulkSelection,
    editClient,
    notify,
    patchUnifiedConversation,
    deleteUnifiedConversation,
    applyUnifiedConversationUpdate,
    refreshUnifiedConversationData,
    updateWhatsAppConversationState,
  });

  const {
    activeConversationComments,
    appendActiveConversationComment,
    replyActiveConversationComment,
  } = useActiveConversationComments({
    selectedTelegramConversation,
    activeTelegramClient,
    selectedLiveChatConversation,
    activeLiveChatClient,
    activeUnifiedConversation,
    selectedEmail,
    activeWhatsAppConversation,
    whatsappConversations,
    editClient,
    addEmailComment,
    addEmailReply,
    patchUnifiedConversation,
    refreshUnifiedConversationData,
    addWhatsAppConversationComment,
    updateWhatsAppConversationState,
  });

  const {
    activeFollowUpAt,
    activeFollowUpNote,
    updateActiveConversationFollowUp,
  } = useConversationFollowUp({
    activeUnifiedConversation,
    selectedEmail,
    activeWhatsAppConversation,
    whatsappConversations,
    activeWhatsAppFollowUp,
    language,
    editEmail,
    patchUnifiedConversation,
    applyUnifiedConversationUpdate,
    addWhatsAppConversationComment,
    updateWhatsAppConversationState,
    appendActiveConversationComment,
    notify,
    whatsappFollowUpMarker: WHATSAPP_FOLLOW_UP_MARKER,
  });

  const {
    telegramReply,
    setTelegramReply,
    isSendingTelegramReply,
    isTelegramMessagesLoading,
    loadTelegramMessages,
    sendTelegramReply,
    draftTelegramReply,
    toggleTelegramHumanTakeover,
    liveChatReply,
    setLiveChatReply,
    isSendingLiveChatReply,
    sendLiveChatReply,
    toggleLiveChatHumanTakeover,
    isRunningLiveChatAgent,
    runSelectedLiveChatAgent,
  } = useConversationReplyActions({
    language,
    selectedTelegramConversation,
    setSelectedTelegramConversation,
    setTelegramMessages,
    selectedLiveChatConversation,
    setSelectedLiveChatConversation,
    activeLiveChatSession,
    activeTelegramClient,
    activeTelegramAgentContext,
    llmMappings,
    activeLLMId,
    llmConfigs,
    sendLiveChatOperatorMessage,
    updateLiveChatSession,
    runLiveChatAgent,
    fetchLiveChatMessages,
    patchUnifiedConversation,
    refreshUnifiedConversationData,
    notify,
  });

  const {
    handleSelect,
    handleSelectWhatsApp,
    handleSelectUnifiedConversation,
    handleDeleteWhatsAppConversation,
    startNewWhatsApp,
    selectWhatsAppContactOption,
    handleCreateLead,
  } = useInboxNavigationActions({
    whatsappConversations,
    unifiedConversationSource,
    selectedEmail,
    selectedEmailId,
    selectedWhatsAppPhone,
    selectedLiveChatConversation,
    selectedTelegramConversation,
    activeLiveChatClient,
    activeLiveChatContactMethod,
    activeTelegramClient,
    activeTelegramContactMethod,
    newWhatsAppPhone,
    markEmailRead,
    selectEmail,
    setIsComposing,
    setComposeDefaults,
    setIsStartingWhatsApp,
    setSelectedWhatsAppPhone,
    setSelectedWhatsAppClientId,
    setSelectedTelegramConversation,
    setTelegramMessages,
    setTelegramReply,
    setSelectedLiveChatConversation,
    setLiveChatReply,
    setWhatsappConversations,
    setNewWhatsAppPhone,
    setShowWhatsAppContactPicker,
    setChannelFilter,
    setIsCreatingLead,
    setConfirmDialog,
    findEmailUnifiedConversation,
    patchUnifiedConversation,
    deleteUnifiedConversation,
    refreshUnifiedConversationData,
    loadTelegramMessages,
    fetchLiveChatMessages,
    fetchLiveChatSessions,
    notify,
  });

  const {
    addingToRag,
    addedToRagId,
    submitTodo,
    submitTag,
    toggleImportant,
    handleAddToRag,
  } = useEmailQuickActions({
    selectedEmail,
    emails,
    todoModalEmail,
    todoAt,
    todoNote,
    tagModalEmail,
    tagInput,
    language,
    llmMappings,
    activeLLMId,
    llmConfigs,
    setTodoModalEmail,
    setTodoAt,
    setTodoNote,
    setTagModalEmail,
    setTagInput,
    setActiveMenu,
    editEmail,
    addKnowledgeItem,
    findEmailUnifiedConversation,
    patchUnifiedConversation,
    refreshUnifiedConversationData,
    notify,
  });

  const contentPanelProps = useInboxContentPanelProps({
    isComposing,
    composeDefaults,
    setIsComposing,
    isStartingWhatsApp,
    setIsStartingWhatsApp,
    newWhatsAppPhone,
    visibleWhatsAppContactOptions,
    setNewWhatsAppPhone,
    setShowWhatsAppContactPicker,
    selectedWhatsAppClientId,
    setSelectedWhatsAppClientId,
    selectWhatsAppContactOption,
    startNewWhatsApp,
    selectedTelegramConversation,
    language,
    activeTelegramClient,
    activeTelegramContactMethod,
    activeTelegramDisplayName,
    activeTelegramTranslateEnabled,
    activeTelegramTranslations,
    activeTelegramAgentContext,
    currentUser,
    telegramMessages,
    isTelegramMessagesLoading,
    translatingConversationMessageIds,
    activeConversationComments,
    commentText,
    telegramReply,
    isSendingTelegramReply,
    activeFollowUpAt,
    activeFollowUpNote,
    setSelectedTelegramConversation,
    setTelegramMessages,
    selectClient,
    updateConversationOwnerStage,
    setConfirmDialog,
    deleteUnifiedConversation,
    refreshUnifiedConversationData,
    toggleTelegramHumanTakeover,
    setConversationAutoTranslateEnabled,
    handleCreateLead,
    setIsAddingContactToClient,
    patchUnifiedConversation,
    applyUnifiedConversationUpdate,
    draftTelegramReply,
    appendActiveConversationComment,
    updateActiveConversationFollowUp,
    setCommentText,
    replyActiveConversationComment,
    setTelegramReply,
    sendTelegramReply,
    selectedLiveChatConversation,
    activeLiveChatClient,
    activeLiveChatContactMethod,
    activeLiveChatSession,
    activeLiveChatTranslateEnabled,
    activeLiveChatTranslations,
    activeLiveChatVisitorInfo,
    activeLiveChatEvidenceItems,
    activeLiveChatAgentContext,
    activeUnifiedConversation,
    visibleLiveChatMessages,
    liveChatReply,
    isSendingLiveChatReply,
    isRunningLiveChatAgent,
    latestLiveChatVisitorMessage,
    liveChatEndRef,
    setSelectedLiveChatConversation,
    toggleLiveChatHumanTakeover,
    runSelectedLiveChatAgent,
    setLiveChatReply,
    sendLiveChatReply,
    selectedWhatsAppPhone,
    setSelectedWhatsAppPhone,
    activeWhatsAppConversation,
    activeWhatsAppClient,
    handleDeleteWhatsAppConversation,
    loadWhatsAppConversations,
    selectedEmail,
    clients,
    isInboundCustomerEmail,
    addingToRag,
    addedToRagId,
    selectedTrackingEvents,
    visibleTrackingEvents,
    isTrackingExpanded,
    selectedEmailAgentContext,
    latestInboundEmailForSelectedClient,
    commentAttachments,
    selectEmail,
    setComposeDefaults,
    handleAddToRag,
    toggleTrackingExpanded,
    editEmail,
    setShowCommentAttachmentModal,
    setCommentAttachments,
  });

  const sidebarProps = useInboxSidebarProps({
    language,
    filter,
    channelFilter,
    search,
    searchTags,
    followUpOnly,
    visibleFollowUpCount,
    unifiedConversationList,
    selectableVisibleCount,
    totalVisibleCount,
    isUnifiedConversationLoading,
    isSyncing,
    isWhatsAppBackgroundSyncing,
    syncError,
    lastSyncAt,
    selectedEmailId,
    selectedWhatsAppPhone,
    selectedTelegramConversation,
    selectedLiveChatConversation,
    selectedConversationIds,
    emails,
    clients,
    currentUser,
    selectedCount,
    allVisibleSelected,
    someVisibleSelected,
    bulkTagInput,
    bulkNoteInput,
    bulkOwnerId,
    bulkStage,
    bulkFollowUpAt,
    onFilterChange: handleFilterChange,
    onChannelFilterChange: handleChannelFilterChange,
    onSearchChange: setSearch,
    onSearchTagsChange: setSearchTags,
    onToggleFollowUpOnly: handleToggleFollowUpOnly,
    onClearFollowUpOnly: handleClearFollowUpOnly,
    onSync: handleSync,
    onToggleSelectAll: toggleSelectAll,
    onClearSelection: clearBulkSelection,
    onBulkTagInputChange: setBulkTagInput,
    onBulkNoteInputChange: setBulkNoteInput,
    onBulkOwnerIdChange: setBulkOwnerId,
    onBulkStageChange: setBulkStage,
    onBulkFollowUpAtChange: setBulkFollowUpAt,
    onAddTag: handleBulkAddTag,
    onAddComment: handleBulkAddComment,
    onAssignOwner: handleBulkAssignOwner,
    onSetStage: handleBulkSetStage,
    onSetFollowUp: handleBulkSetFollowUp,
    onMarkImportant: handleBulkMarkImportant,
    onDeleteSelected: handleDeleteSelected,
    onSelectConversation: handleSelectUnifiedConversation,
    onToggleConversationSelection: toggleUnifiedSelection,
    onDeleteWhatsAppConversation: handleDeleteWhatsAppConversation,
    onOwnerStageChange: updateConversationOwnerStage,
    onComposeEmail: handleComposeEmail,
    onStartWhatsApp: handleStartWhatsApp,
  });

  const dialogLayerProps = useInboxDialogLayerProps({
    isCreatingLead,
    isAddingContactToClient,
    filter,
    selectedEmail,
    selectedTelegramConversation,
    selectedLiveChatConversation,
    activeTelegramDisplayName,
    activeLiveChatDisplayName,
    activeTelegramContactMethod,
    activeLiveChatContactMethod,
    activeLinkableContactMethod,
    activeLinkableDisplayName,
    activeUnifiedConversation,
    patchUnifiedConversation,
    setSelectedTelegramConversation,
    setSelectedLiveChatConversation,
    updateLiveChatSession,
    fetchLiveChatSessions,
    refreshUnifiedConversationData,
    editEmail,
    selectClient,
    confirmDialog,
    alertDialog,
    showCommentAttachmentModal,
    tagModalEmail,
    tagInput,
    todoModalEmail,
    todoAt,
    todoNote,
    setIsCreatingLead,
    setIsAddingContactToClient,
    setConfirmDialog,
    setAlertDialog,
    setShowCommentAttachmentModal,
    setCommentAttachments,
    setTagInput,
    submitTag,
    setTagModalEmail,
    setTodoAt,
    setTodoNote,
    submitTodo,
    setTodoModalEmail,
  });

  const { sidebarHidden, contentHidden } = useInboxPageVisibility({
    selectedEmailId,
    selectedWhatsAppPhone,
    selectedTelegramConversation,
    selectedLiveChatConversation,
    isComposing,
    isStartingWhatsApp,
  });

  return (
    <InboxPageShell
      sidebarHidden={sidebarHidden}
      contentHidden={contentHidden}
      sidebarProps={sidebarProps}
      contentPanelProps={contentPanelProps}
      dialogLayerProps={dialogLayerProps}
    />
  );
}

export { ComposeEmail } from './inbox-ui';
